#!/bin/bash

request=$1
comment_filter=$2

config_file=~/.pureApiTestConfig

./setup.sh
wait

source read_config.sh

# If no request is specified, list all requests
# Else, list responses to request with specified id
if [ -z $request ]
then
    sqlite3 -init requests_sqlite_options.txt $db_path\
        "SELECT * FROM requests;"
else
    re='^[0-9]+$'
    if [[ $request =~ $re ]]
    then
        if [ -z $comment_filter ]
        then
            sqlite3 -init responses_sqlite_options.txt $db_path\
                "SELECT * FROM responses WHERE request_id=$request;"
        else
            sqlite3 -init responses_sqlite_options.txt $db_path\
                "SELECT * FROM responses WHERE request_id=$request AND comment
                            LIKE '%$comment_filter%';"
        fi
    else
        echo "Request ID should be an integer"
        exit 1
    fi
fi
