#!/bin/bash

request=$1

config_file=~/.pureApiTestConfig

./setup.sh
wait

# Read the data directory from config file
data_dir="$(grep '^data_dir' $config_file | cut -d'=' -f2)"

# Avoid tilde expansion issues later on
data_dir="$(eval echo ${data_dir})"

# DB details
db_file="pureApiTest.sqlite"
db_path="$data_dir/$db_file"

# If no request is specified, list all requests
# Else, list responses to request with specified id
if [ -z $request ]
then
    sqlite3 -init requests_sqlite_options.txt $db_path\
        "SELECT * FROM requests;"
else
    re='^[0-9]+$'
    if [[ $request =~ $re ]]
    then
        sqlite3 -init responses_sqlite_options.txt $db_path\
            "SELECT * FROM responses WHERE request_id=$request;"
    fi
fi
